version: '2.0'

services:
  statistics-counter-db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_PASSWORD: 12qwaszx
      POSTGRES_USER: project_db_user
      POSTGRES_DB: project_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "python manage.py migrate &&
                    gunicorn source.wsgi -b 0.0.0.0:9090"
    depends_on:
      - statistics-counter-db
    environment:
      - DB_HOST=statistics-counter-db
      - DB_USER=project_db_user
      - DB_PASS=12qwaszx
      - DB_NAME=project_db
      - DB_PORT=5432
      - API_SECURE_KEY=ENtqH5i7DP22Mcenu1u6Ok7diyTCVLFmKzT1vlXyOTlirIf4yG
      - DEBUG=True
    volumes:
      - ./static:/static


  nginx:
      restart: always
      image: nginx:alpine
      container_name: statistics-counter-nginx
      depends_on:
        - web
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./static:/etc/nginx/conf.d/static
      environment:
        TZ: "Asia/Bishkek"
      ports:
        - 9090:9090
      logging:
          driver: "json-file"
          options:
              max-file: "5"
              max-size: "100m"
