# Generated by Django 3.2.7 on 2021-09-29 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество показов')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Количество откликов')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Стоимсть откликов в рублях')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
                'db_table': 'statistic',
            },
        ),
    ]
